require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'db/schema.rb'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 24

Metrics/BlockLength:
  Max: 24
  Exclude:
    - 'config/environments/*'

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  CountAsOne:
    - array
    - hash
    - heredoc
  Max: 10
