require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 24

Style/Documentation:
  Enabled: false
