AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 24

Metrics/BlockLength:
  Max: 24
  Exclude:
    - 'config/environments/*'

Style/Documentation:
  Enabled: false
